content_type:
  - definition
  - explanation
  - example
  - methodology
  - case_study
  - summary
  - introduction
  - conclusion
  - instruction
  - question
  - opinion
  - statement_of_fact
  - critique
  - comparison
  - analysis

complexity:
  - beginner
  - intermediate
  - advanced
  - expert

actionability:
  - actionable
  - theoretical
  - reference
  - practical_exercise
  - checklist
  - template
  - framework
  - tool
