
concepts:
  - ethics
  - epistemology
  - ontology
  - phenomenology
  - hermeneutics
  - existentialism
  - recognition
  - selfhood
  - intersubjectivity
  - trauma
  - developmental_morality
  - systems_thinking

philosophical_methods:
  - analytical
  - dialectical
  - phenomenological
  - pragmatic
  - dialogical
  - developmental
  - systems_theoretical
  - second_order_observation
