philosophical_schools:
- phenomenology
- existentialism
- analytic_philosophy
- continental_philosophy
- pragmatism
- stoicism
- empiricism
- rationalism
- idealism
- materialism
- postmodernism
- structuralism
- poststructuralism
- critical_theory
- hermeneutics
- dialectical_materialism
- humanism
- utilitarianism
- virtue_ethics
- deconstruction


concepts:
- aesthetics
- being
- consciousness
- developmental_morality
- epistemology
- ethics
- free_will
- identity
- intersubjectivity
- knowledge
- logic
- meaning
- metaphysics
- morality
- ontology
- reality
- recognition
- selfhood
- systems_thinking
- trauma
- truth

thinkers:
- aristotle
- plato
- kant
- hegel
- nietzsche
- heidegger
- wittgenstein
- descartes
- hume
- locke
- spinoza
- sartre
- camus
- foucault
- derrida

philosophical_methods:
- analytical
- deconstructive
- developmental
- dialectical
- dialogical
- empirical
- hermeneutical
- phenomenological
- pragmatic
- rational
- second_order_observation
- systems_theoretical
