methodologies:
  - agile
  - scrum
  - kanban
  - waterfall
  - lean
  - six_sigma
  - prince2
  - pmbok
  - safe
  - devops

phases:
  - initiation
  - planning
  - execution
  - monitoring
  - closure
  - retrospective

concepts:
  - scope_management
  - time_management
  - cost_management
  - quality_management
  - risk_management
  - communication
  - stakeholder_management
  - resource_management
  - procurement
  - integration

tools:
  - gantt_charts
  - burndown_charts
  - kanban_boards
  - risk_registers
  - stakeholder_matrix
  - work_breakdown_structure
  - critical_path_method
  - earned_value_management

roles:
  - project_manager
  - product_owner
  - scrum_master
  - team_lead
  - stakeholder
  - sponsor
  - business_analyst
  - technical_lead

deliverables:
  - project_charter
  - requirements
  - specifications
  - timeline
  - budget
  - status_report
  - lessons_learned
  - documentation
