pipeline:
  - pdf_parse
  - text_clean
  - heading_detect
  - split_semantic
  - emit_jsonl

options:
  pdf_parse:
    engine: "native"
  text_clean:
    normalize_quotes: true
    repair_ligatures: true
  split_semantic:
    target_tokens: 800
    hard_page_boundaries: false
    generate_metadata: true
  ai_enrich:
    enabled: false
    tags_file: "tags.yaml"
  emit_jsonl:
    output_path: "out.jsonl"
